[[headers]]
    for = '/*'
    [headers.values]
        Access-Control-Allow-Origin = "*"
        Access-Control-Allow-Headers = "Content-Type"
        Access-Control-Allow-Methods = "GET, POST, PUT, DELETE"

[build]
    functions = "netlify/functions"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200